name:                cis-one-nine-four-spring-thirteen
version:             0.1.0.0
github:              "githubuser/cis-194"
license:             GPL-3.0
author:              "Laura Viglioni"
maintainer:          "l106665@dac.unicamp.br"
copyright:           "2021 Laura Viglioni"

extra-source-files:
- README.org
description:         Please see the README on GitHub at <https://github.com/githubuser/#readme>

dependencies:
- base >= 4.7 && < 5
        
executables:
  cis-one-nine-four-spring-thirteen-exe:
    main:                HelloWorld.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
