
name:                regev-cryptosystem-lol
version:             0.1.0.0
github:              "githubuser/regev-cryptosystem-lol"
license:             BSD3
author:              "Laura Viglioni"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/regev-cryptosystem-lol#readme>

dependencies:
- base >= 4.7 && < 5
- lol
        

library:
  source-dirs: src

executables:
  regev-cryptosystem-lol-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regev-cryptosystem-lol

tests:
  regev-cryptosystem-lol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regev-cryptosystem-lol
