* Regev Crypto System
** About
   - This project aims to implement the cryptosystem proposed by Oded Regev: [[https://people.csail.mit.edu/vinodv/6892-Fall2013/regev.pdf][On Lattices, Learning with Errors, Random Linear Codes, and Cryptography]] using LoL lib.
   - Work in progress.
** Lol docs
   - Lol docs on [[https://hackage.haskell.org/package/lol][hackage]]
   - Lol repo on [[https://github.com/cpeikert/Lol][github]]
   - Lol docs [[https://eprint.iacr.org/2015/1134.pdf][paper]]
* Creating new project with LoL
** Pre-recs
   You need to install cabal and stack. There are several ways to do it, I think installing [[https://www.haskell.org/ghcup/#][ghcup]] is enough.
   For better use of LSP on your editor etc I've downloaded also these packages:
   #+begin_src shell :exports both 
     cabal install apply-refact hlint stylish-haskell hasktags hoogle hindent implicit-hie
   #+end_src
  
** Steps
*** Creating a project with stack
    - Checkout docs https://docs.haskellstack.org/en/stable/GUIDE/
    - ~stack new [your-project-name] new-template~
*** To enhance your project configs
    - Create on the root of the project a file called ~hie.yaml~:
      #+begin_src yaml :exports both 
          cradle:
            stack:
        
      #+end_src
*** Add Lol to the project
    - On your ~package.yaml~:
      #+begin_src yaml :exports both 
          dependencies:
            - base >= 4.7 && < 5
            - lol
        
      #+end_src

    - On your ~stack.yaml~:
      #+begin_src yaml :exports both 
        
        resolver:
          url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/15.yaml
        
          extra-deps:
            - git: https://github.com/cpeikert/Lol.git
              commit: 9da805f3d3be7fed6e5276cfd2aafe0894dcd14d
              subdirs:
                - lol
                - monadcryptorandom-0.7.2.1
      #+end_src
* Build
  - After following the steps above
    #+begin_src shell :exports both 
      stack build
    #+end_src
* Run
  - After building
    #+begin_src shell :exports both 
      stack exec regev-cryptosystem-lol-exe
    #+end_src
